version: '3.0'
services:
  postgres: # 相关文档 https://hub.docker.com/_/postgres
    # 容器名称
    container_name: postgres
    build:
      context: .
      args:
        - PGSQL_VER=15
    volumes:
      - ../data/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "root"
    restart: always
    networks:
        - services_default

networks:
    services_default:
      external: true