version: '3'
services:
  nats:
    image: nats:2.9.21
    container_name: nats
    ports:
      - 4222:4222
    restart: always
    networks:
      - services_default

networks:
    services_default:
      external: true