version: "3"
services:
  kafka:
      image: 'bitnami/kafka:3.6.1'
      networks:
      - services_default
      container_name: kafka
      restart: always
      user: root
      ports:
        - "9092:9092"
        - "9093:9093"
      environment:
        - KAFKA_ENABLE_KRAFT=yes # 允许使用kraft，即Kafka替代Zookeeper
        - KAFKA_CFG_PROCESS_ROLES=broker,controller # kafka角色，做broker，也要做controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER # 指定供外部使用的控制类请求信息
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 # 定义kafka服务端socket监听端口
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT # 定义安全协议
        - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 # 集群地址
        - ALLOW_PLAINTEXT_LISTENER=yes # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
        - KAFKA_HEAP_OPTS=-Xmx256M -Xms256M # 设置broker最大内存，和初始内存
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false # 禁止自动创建主题
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.27.80.1:9092 # 定义外网访问地址（宿主机ip地址和端口）
        - KAFKA_BROKER_ID=1 # broker.id，必须唯一
        - KAFKA_CFG_NODE_ID=1
        - BITNAMI_DEBUG=true
      volumes:
        - ../../data/kafka:/bitnami/kafka

networks:
  services_default:
    external: true